name: expert_flutter_dicoding
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Network
  http: ^1.1.0
  # Local Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  # State Management
  provider: ^6.1.1
  # Functional Programming
  dartz: ^0.10.1
  # Dependency Injection
  get_it: ^8.0.3
  # Object Comparison
  equatable: ^2.0.5
  # Image Caching
  cached_network_image: ^3.3.0
  # Google Fonts
  google_fonts: ^6.1.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Testing
  mockito: ^5.4.2
  build_runner: ^2.4.6
  sqflite_common_ffi: ^2.3.0
  fake_async: ^1.3.1

flutter:
  uses-material-design: true
