// Mocks generated by Mockito 5.4.6 from annotations
// in expert_flutter_dicoding/test/data/repositories/tv_series_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:expert_flutter_dicoding/data/datasources/tv_series_local_data_source.dart'
    as _i5;
import 'package:expert_flutter_dicoding/data/datasources/tv_series_remote_data_source.dart'
    as _i3;
import 'package:expert_flutter_dicoding/data/models/tv_series_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvSeriesModel_0 extends _i1.SmartFake implements _i2.TvSeriesModel {
  _FakeTvSeriesModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i3.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TvSeriesModel>> getNowPlayingTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingTvSeries,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.TvSeriesModel>>.value(<_i2.TvSeriesModel>[]),
      ) as _i4.Future<List<_i2.TvSeriesModel>>);

  @override
  _i4.Future<List<_i2.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvSeries,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.TvSeriesModel>>.value(<_i2.TvSeriesModel>[]),
      ) as _i4.Future<List<_i2.TvSeriesModel>>);

  @override
  _i4.Future<List<_i2.TvSeriesModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvSeries,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.TvSeriesModel>>.value(<_i2.TvSeriesModel>[]),
      ) as _i4.Future<List<_i2.TvSeriesModel>>);

  @override
  _i4.Future<_i2.TvSeriesModel> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesDetail,
          [id],
        ),
        returnValue: _i4.Future<_i2.TvSeriesModel>.value(_FakeTvSeriesModel_0(
          this,
          Invocation.method(
            #getTvSeriesDetail,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.TvSeriesModel>);

  @override
  _i4.Future<List<_i2.TvSeriesModel>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesRecommendations,
          [id],
        ),
        returnValue:
            _i4.Future<List<_i2.TvSeriesModel>>.value(<_i2.TvSeriesModel>[]),
      ) as _i4.Future<List<_i2.TvSeriesModel>>);

  @override
  _i4.Future<List<_i2.TvSeriesModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [query],
        ),
        returnValue:
            _i4.Future<List<_i2.TvSeriesModel>>.value(<_i2.TvSeriesModel>[]),
      ) as _i4.Future<List<_i2.TvSeriesModel>>);
}

/// A class which mocks [TvSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDataSource extends _i1.Mock
    implements _i5.TvSeriesLocalDataSource {
  MockTvSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> insertWatchlist(_i2.TvSeriesModel? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [tvSeries],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #insertWatchlist,
            [tvSeries],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> removeWatchlist(_i2.TvSeriesModel? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [tvSeries],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [tvSeries],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.TvSeriesModel?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesById,
          [id],
        ),
        returnValue: _i4.Future<_i2.TvSeriesModel?>.value(),
      ) as _i4.Future<_i2.TvSeriesModel?>);

  @override
  _i4.Future<List<_i2.TvSeriesModel>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvSeries,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.TvSeriesModel>>.value(<_i2.TvSeriesModel>[]),
      ) as _i4.Future<List<_i2.TvSeriesModel>>);
}
